import SideMenu from './components/SideMenu/SideMenu';
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className='flex bg-globalBackground'>
        <SideMenu/>
        {children}
      </body>
    </html>
  );
}
