import SideMenu from './components/SideMenu/SideMenu';
import SideMenuFromRestaurant from './components/SideMenu/SideMenuFromRestaurant';
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru">
      <body className='flex bg-globalBackground'>
        {/* <SideMenu/> */}
        <SideMenuFromRestaurant/>
        {children}
      </body>
    </html>
  );
}
