import SideMenu from './components/SideMenu/SideMenu';
import SideMenuFromRestaurant from './components/SideMenu/SideMenuFromRestaurant';
import { GetWidthProvider } from './context/GetWidth/GetWidth';
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <GetWidthProvider>
      <html lang="ru">
        <body className='flex bg-globalBackground pl-[191px]- pl-[464px]'>
          <SideMenu/>
          {/* <SideMenuFromRestaurant/> */}
          {children}
        </body>
      </html>
    </GetWidthProvider>
  );
}
